### ISSUE TITLE
多次部署函数报错

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc-deploy#52]
场景描述：
1. 部署服务及函数, yaml 如下
````
edition: 1.0.0
name: functionApp

services:
  laravelExample:
    component: devsapp/fc-deploy
    props:
      region: cn-shenzhen
      service:
        name: serverless-devs
        description: Serverless Devs示例程序
        vpcConfig: auto
      function:
        name: test
        runtime: nodejs12
        hanlder: index.hanlder
        code: .
````

2. 再次部署函数，新增配置  logConfig: auto，会失败
````
edition: 1.0.0
name: functionApp

services:
  laravelExample:
    component: devsapp/fc-deploy
    props:
      region: cn-shenzhen
      service:
        name: serverless-devs
        description: Serverless Devs示例程序
        vpcConfig: auto
        logConfig: auto
      function:
        name: test
        runtime: nodejs12
        hanlder: index.hanlder
        code: .
````

3. 不修改配置，删除 .s 目录，再次部署，部署成功
